version: '3.1'
services:
  boundless:
    build: .
    container_name: boundless
    ports:
      - "${DOCKER_BOUNDLESS_PORT}:8080"
  postgis:
    image: "mdillon/postgis"
    container_name: boundless_postgis
    environment:
      POSTGRES_USER: ${DOCKER_POSTGIS_USER}
      POSTGRES_PASSWORD: ${DOCKER_POSTGIS_PASSWORD}
    ports:
      - "${DOCKER_POSTGIS_PORT}:5432"
